# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Applicants',
            fields=[
                ('idnum', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('year', models.TextField(blank=True, db_column='Year', null=True)),
                ('reference_no', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('ad_round', models.TextField(blank=True, null=True)),
                ('ad_result', models.TextField(blank=True, null=True)),
                ('ad_supervisor', models.TextField(blank=True, null=True)),
                ('ad_group', models.TextField(blank=True, null=True)),
                ('ad_degree', models.TextField(blank=True, null=True)),
                ('ad_hkpf', models.TextField(blank=True, null=True)),
                ('ad_scholarship', models.TextField(blank=True, null=True)),
                ('gender', models.TextField(blank=True, null=True)),
                ('apply_for', models.TextField(blank=True, null=True)),
                ('university_ug', models.TextField(blank=True, null=True)),
                ('qs_ug', models.IntegerField(blank=True, db_column='QS_ug', null=True)),
                ('qs_on_ug', models.IntegerField(blank=True, db_column='QS_on_ug', null=True)),
                ('major_ug', models.TextField(blank=True, null=True)),
                ('major_ug_other', models.TextField(blank=True, null=True)),
                ('gpa_ug', models.FloatField(blank=True, null=True)),
                ('gpa_ug_scale', models.IntegerField(blank=True, null=True)),
                ('rank_ug', models.TextField(blank=True, null=True)),
                ('university_pg', models.TextField(blank=True, null=True)),
                ('qs_pg', models.IntegerField(blank=True, db_column='QS_pg', null=True)),
                ('qs_on_pg', models.IntegerField(blank=True, db_column='QS_on_pg', null=True)),
                ('major_pg', models.TextField(blank=True, null=True)),
                ('major_pg_other', models.TextField(blank=True, null=True)),
                ('gpa_pg', models.FloatField(blank=True, null=True)),
                ('gpa_pg_scale', models.IntegerField(blank=True, null=True)),
                ('rank_pg', models.TextField(blank=True, null=True)),
                ('interest1', models.TextField(blank=True, db_column='Interest1', null=True)),
                ('interest2', models.TextField(blank=True, db_column='Interest2', null=True)),
                ('interest3', models.TextField(blank=True, db_column='Interest3', null=True)),
                ('english_tests', models.TextField(blank=True, null=True)),
                ('papers', models.IntegerField(blank=True, null=True)),
                ('hc', models.TextField(blank=True, null=True)),
                ('tc', models.TextField(blank=True, null=True)),
                ('toc', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('toefl', models.IntegerField(blank=True, null=True)),
                ('cet6', models.IntegerField(blank=True, db_column='CET6', null=True)),
                ('shortlisted', models.IntegerField(blank=True, null=True)),
                ('norm_gpa_ug', models.FloatField(blank=True, null=True)),
                ('norm_gpa_pg', models.FloatField(blank=True, null=True)),
                ('qsranking', models.IntegerField(blank=True, db_column='QSRanking', null=True)),
                ('onqsranking', models.IntegerField(blank=True, db_column='onQSRanking', null=True)),
            ],
            options={
                'db_table': 'applicants',
            },
        ),
        migrations.CreateModel(
            name='Applicants2016',
            fields=[
                ('reference_no', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('apply_for', models.CharField(blank=True, max_length=10, null=True)),
                ('university_ug', models.CharField(blank=True, max_length=30, null=True)),
                ('major_ug', models.CharField(blank=True, max_length=10, null=True)),
                ('major_ug_other', models.CharField(blank=True, max_length=30, null=True)),
                ('gpa_ug', models.FloatField(blank=True, null=True)),
                ('gpa_ug_scale', models.FloatField(blank=True, null=True)),
                ('rank_ug', models.CharField(blank=True, max_length=20, null=True)),
                ('university_pg', models.CharField(blank=True, max_length=30, null=True)),
                ('major_pg', models.CharField(blank=True, max_length=10, null=True)),
                ('major_pg_other', models.CharField(blank=True, max_length=30, null=True)),
                ('gpa_pg', models.FloatField(blank=True, null=True)),
                ('gpa_pg_scale', models.FloatField(blank=True, null=True)),
                ('rank_pg', models.CharField(blank=True, max_length=20, null=True)),
                ('interest1', models.CharField(blank=True, db_column='Interest1', max_length=10, null=True)),
                ('interest2', models.CharField(blank=True, db_column='Interest2', max_length=10, null=True)),
                ('interest3', models.CharField(blank=True, db_column='Interest3', max_length=10, null=True)),
                ('english_tests', models.CharField(blank=True, max_length=50, null=True)),
                ('papers', models.IntegerField(blank=True, null=True)),
                ('hc', models.TextField(blank=True, null=True)),
                ('tc', models.TextField(blank=True, null=True)),
                ('toc', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('toefl', models.IntegerField(blank=True, null=True)),
                ('cet6', models.IntegerField(blank=True, db_column='CET6', null=True)),
                ('shortlisted', models.IntegerField(blank=True, null=True)),
                ('norm_gpa_ug', models.FloatField(blank=True, null=True)),
                ('norm_gpa_pg', models.FloatField(blank=True, null=True)),
                ('qsranking', models.IntegerField(blank=True, db_column='QSRanking', null=True)),
                ('onqsranking', models.IntegerField(blank=True, db_column='onQSRanking', null=True)),
            ],
            options={
                'db_table': 'applicants2016',
            },
        ),
    ]
