# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 03:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mining1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicants',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='applicants2016',
            options={'managed': True},
        ),
    ]
