# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-07 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mining1', '0002_auto_20170326_0307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicants',
            options={'managed': False},
        ),
    ]
